language: python

addons:
  chrome: stable

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=linting
    - python: 3.7
      env: TOXENV=formatting
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=typechecking

install:
    - pip install tox

script:
    - tox
